# Generated by Django 5.2.4 on 2025-07-17 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_category_transaction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-date']},
        ),
    ]
